### ISSUE TITLE
Crashes randomly upon game initalization

### ISSUE THREAD

**Issue by ghost** [somewhatlurker/DivaSound#3]
The game initialization is completely RNG if it success with the latest version 2.1.
Earlier versions such as 1.1 used the game audio initialization function instead of it's own function in the current version, I can confirm the game always initializes correctly with the first method.

**Comment by somewhatlurker** [comment]
I'd still like to investigate the reason behind this for a future version, but after two very crash-prone releases (for some users) I have reverted to using the old initialisation by default with a configurable option to use the new one.  
Hopefully this completely addresses the issue.
